language: python
python:
  - "3.9"
cache: pip
install: 
 - pip install -U setuptools
 - pip install -r requirements.txt
 - pip install coveralls
# command to run tests
script:
 - py.test --cov=crypto_reflex ./crypto_reflex/tests.py
after_success:
 - coveralls